# -*- coding: utf-8 -*-
"""ComparingBasicNNArchitectures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBXR4DF-4OQBVCTbNhe831gxtCf2cET0

* K-Fold cross validation with 6 splits.
"""

# Import core modules
from tensorflow import keras
from keras.datasets import mnist
import numpy as np
from sklearn.model_selection import StratifiedKFold

# 1. Load the data, split between train and test sets
# The MNIST dataset already provides a split of 60,000 for training and 10,000 for testing
(x_train, y_train), (x_test, y_test) = mnist.load_data()
# x is the input data
# y is the labels

# Print the original shape to verify (expecting 60000 images of 28x28 pixels)
print('Original train shape:', x_train.shape)
print('Original test shape:', x_test.shape)

# 2. Normalize the data in range [0, 1]
# A grayscale image has pixel values in[0, 255]
x_train = x_train / 255.0
x_test = x_test / 255.0

# 3. Add a channel dimension (needed for CNNs)
# Images are 2D (28x28), we make them 3D (28x28x1) where 1 is the grayscale channel
x_train = np.expand_dims(x_train, axis=-1)
x_test = np.expand_dims(x_test, axis=-1)

print('Shape after adding channel dimension:', x_train.shape)

# Save the original labels before One-Hot Encoding
# (StratifiedKFold needs the original 1D labels to split evenly)
y_train_original = y_train.copy()

# 4. Do a one-hot-encoding for the outputs (labels)
# We have 10 classes (digits 0-9)
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

# 5. Define the K-Fold cross validation process
# We use StratifiedKFold with 6 splits, as requested by the assignment
k_folds = 6
skf = StratifiedKFold(n_splits=k_folds, shuffle=True, random_state=42)

print("Data preprocessing and K-Fold setup completed successfully!")

"""* DNN Architecture (Βήμα 2ο)"""

from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten

# Define a function that creates the DNN architecture
def create_dnn_model():
    # 1. Initialize the Neural Network (Sequential means layers are added one after another)
    model = Sequential()

    # 2. Flatten layer: Converts the 28x28 2D image into a flat 1D array of 784 pixels
    # DNNs (unlike CNNs) require the data to be in a single straight line.
    model.add(Flatten(input_shape=(28, 28, 1)))

    # 3. First Hidden Layer (Dense means fully connected)
    # Rule 2b: Use 'relu' activation function
    model.add(Dense(128, activation='relu'))

    # 4. Dropout Layer
    # Rule 2c: Use at least one dropout layer. We drop 20% of neurons to prevent overfitting.
    model.add(Dropout(0.2))

    # 5. Second Hidden Layer
    # Again using 'relu' as requested by the assignment
    model.add(Dense(64, activation='relu'))

    # 6. Output Layer
    # We have 10 digits (0-9), so we need 10 output neurons.
    # Rule 2d: Output layer MUST use 'softmax'
    model.add(Dense(10, activation='softmax'))

    # 7. Compile the model
    # We use 'categorical_crossentropy' because our labels are One-Hot Encoded (Step 1)
    # We use 'adam' optimizer (a standard, fast way for the network to update its weights)
    # We track 'accuracy' to see how many digits it guessed correctly
    model.compile(loss='categorical_crossentropy',
                  optimizer='Adam',
                  metrics=['accuracy'])

    return model

# Test the function by creating a model and printing its summary
test_dnn = create_dnn_model()
print("DNN Architecture Summary:")
test_dnn.summary()

"""* CNN Architecture"""

from keras.layers import Conv2D, MaxPooling2D

# Define a function that creates the CNN architecture
def create_cnn_model():
    model = Sequential()

    # 1. First Convolutional Layer
    # It uses 6 filters of size 3x3. It reads the 28x28x1 image.
    # Rule 2b: Use 'relu' activation
    model.add(Conv2D(6, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)))

    # 2. First Pooling Layer
    # Shrinks the image by taking the maximum value in every 2x2 window
    model.add(MaxPooling2D(pool_size=(2, 2)))

    # 3. Second Convolutional Layer
    # Now we use 12 filters of size 3x3 to find more complex patterns
    model.add(Conv2D(12, kernel_size=(3, 3), activation='relu'))

    # 4. Second Pooling Layer
    # Shrinks the feature maps again
    model.add(MaxPooling2D(pool_size=(2, 2)))

    # 5. Flatten Layer
    # Now that the CNN has found the patterns, we flatten the output
    # to feed it into a standard Dense network for the final decision
    model.add(Flatten())

    # 6. Hidden Dense Layer
    model.add(Dense(128, activation='relu'))

    # 7. Dropout Layer
    # Added to satisfy Rule 2c: use at least one dropout layer.
    model.add(Dropout(0.25))

    # 8. Output Layer
    # 10 output digits (0-9). Rule 2d: Output layer MUST use 'softmax'
    model.add(Dense(10, activation='softmax'))

    # 9. Compile the model
    model.compile(loss='categorical_crossentropy',
                  optimizer='Adam',
                  metrics=['accuracy'])

    return model

# Test the function by creating a model and printing its summary
test_cnn = create_cnn_model()
print("CNN Architecture Summary:")
test_cnn.summary()

"""* Training of DNN & CNN - Βήμα 3ο"""

import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
import numpy as np

# 1. Initialize an empty list to store the results of each experiment
results_list =[]

# Variables to keep track of the highest Test Accuracy for both models
best_dnn_acc = 0
best_cnn_acc = 0

# The Test Set labels are currently One-Hot encoded [0,0,0,1,...]
# We need them as simple digits [3] to calculate the metrics easily
y_test_true = np.argmax(y_test, axis=1)

# Set the number of epochs (how many times the network reads the data per fold)
# We set it to 5 for speed. You can increase it to 10 or 20 later if you want.
EPOCHS = 5

# 2. Start the K-Fold Loop
# skf.split will divide the 60,000 images into 50k for training and 10k for validation
for fold_index, (train_idx, val_idx) in enumerate(skf.split(x_train, y_train_original)):
    fold_num = fold_index + 1
    print(f"\n{'='*40}")
    print(f"Starting Fold {fold_num} / 6")
    print(f"{'='*40}")

    # 2a. Create the independent Train and Validation sets for this specific fold
    x_fold_train = x_train[train_idx]
    y_fold_train = y_train[train_idx]

    x_fold_val = x_train[val_idx]
    y_fold_val = y_train[val_idx]

    # Convert one-hot labels back to normal digits for the Train metrics later
    y_fold_train_true = np.argmax(y_fold_train, axis=1)

    # We will run the exact same process for both DNN and CNN
    for technique in['DNN', 'CNN']:
        print(f"\n--- Training {technique} (Fold {fold_num}) ---")

        # 3. Create a fresh model
        if technique == 'DNN':
            model = create_dnn_model()
        else:
            model = create_cnn_model()

        # 4. Train the model using the Validation set
        # Rule 3b: validation data must be independent.
        history = model.fit(x_fold_train, y_fold_train,
                            validation_data=(x_fold_val, y_fold_val),
                            epochs=EPOCHS,
                            batch_size=128,
                            verbose=1) # verbose=1 prints the loss on the screen

        # 5. Plot the Training and Validation Loss Curves
        # Rule 3c: Plot training history
        plt.figure(figsize=(8, 4))
        plt.plot(history.history['loss'], label='Train Loss', color='blue')
        plt.plot(history.history['val_loss'], label='Validation Loss', color='orange')
        plt.title(f'{technique} Loss Curve - Fold {fold_num}')
        plt.ylabel('Loss')
        plt.xlabel('Epoch')
        plt.legend()
        plt.show()

        # 6. Predict on Train and Test Sets
        # Predict on the current Train set
        train_predictions = model.predict(x_fold_train)
        train_pred_classes = np.argmax(train_predictions, axis=1)

        # Predict on the official Test set (always the 10,000 samples)
        test_predictions = model.predict(x_test)
        test_pred_classes = np.argmax(test_predictions, axis=1)

        # 7. Calculate Metrics (Accuracy, Precision, Recall, F1)
        # We use zero_division=0 to prevent warnings if the network guesses completely wrong initially
        tr_acc = accuracy_score(y_fold_train_true, train_pred_classes)
        tr_prec = precision_score(y_fold_train_true, train_pred_classes, average='macro', zero_division=0)
        tr_rec = recall_score(y_fold_train_true, train_pred_classes, average='macro', zero_division=0)
        tr_f1 = f1_score(y_fold_train_true, train_pred_classes, average='macro', zero_division=0)

        te_acc = accuracy_score(y_test_true, test_pred_classes)
        te_prec = precision_score(y_test_true, test_pred_classes, average='macro', zero_division=0)
        te_rec = recall_score(y_test_true, test_pred_classes, average='macro', zero_division=0)
        te_f1 = f1_score(y_test_true, test_pred_classes, average='macro', zero_division=0)

        # 8. Save the results as a row in our list
        # Format: Technique name | Set | Fold number | Accuracy | Precision | Recall | F1 score
        results_list.append([f"{technique}", "Train", fold_num, tr_acc, tr_prec, tr_rec, tr_f1])
        results_list.append([f"{technique}", "Test", fold_num, te_acc, te_prec, te_rec, te_f1])

        # 9. Save the best model (.h5) based on Test Accuracy
        # Rule 4: save the DNN and CNN with the best results on the test set across the 6 folds.
        if technique == 'DNN' and te_acc > best_dnn_acc:
            best_dnn_acc = te_acc
            model.save('best_dnn_model.h5')
            print(f"[*] New best DNN saved! (Accuracy: {te_acc:.4f})")

        elif technique == 'CNN' and te_acc > best_cnn_acc:
            best_cnn_acc = te_acc
            model.save('best_cnn_model.h5')
            print(f"[*] New best CNN saved! (Accuracy: {te_acc:.4f})")

# 10. Convert the list of results into a Pandas DataFrame
columns_names =['Technique name', 'Set', 'Fold number', 'Accuracy', 'Precision', 'Recall', 'F1 score']
df_results = pd.DataFrame(results_list, columns=columns_names)

# Save the DataFrame to a CSV file (Rule 3e)
df_results.to_csv('erotima1.csv', index=False)

print("\nAll folds completed successfully!")
print("Results saved to 'erotima1.csv' and best models saved as .h5 files.")

# Display the final DataFrame
display(df_results)

"""* Plot drawing"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read the results file
df = pd.read_csv('erotima1.csv')

# Keep ONLY the Test Set results (these show the true performance)
test_df = df[df['Set'] == 'Test']

# Calculate the mean Accuracy and F1 score for each technique (DNN / CNN)
summary_df = test_df.groupby('Technique name')[['Accuracy', 'F1 score']].mean().reset_index()

# Create the chart (Bar Chart)
fig, ax = plt.subplots(figsize=(8, 5))
summary_df.plot(x='Technique name', y=['Accuracy', 'F1 score'], kind='bar', ax=ax, color=['#4C72B0', '#DD8452'])

# Beautify the chart
plt.title('Comparison of Mean Performance on Test Set (6 Folds)', fontsize=14)
plt.ylabel('Score (0.0 - 1.0)', fontsize=12)
plt.xlabel('Neural Architecture', fontsize=12)
plt.xticks(rotation=0)
plt.legend(['Mean Accuracy', 'Mean F1 Score'])
plt.ylim(0.8, 1.0) # Start Y-axis from 0.8 for better visibility of differences
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Display the chart
plt.show()