# -*- coding: utf-8 -*-
"""ComparingBasicRNNArchitectures

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQQHaBh0708nBOfAp5q15FbGLvGcr7z4

* Importing the libraries
"""

# Import the required libraries
import numpy as np
from google.colab import drive

"""* Importing the data"""

# Mount Google Drive to the Colab environment
drive.mount('/content/drive')

# Define the folder path where the dataset is located in your Google Drive
# IMPORTANT: You must change the path below to match where you saved the files
folder_path = '/content/drive/MyDrive/Colab Notebooks/Neural Networks/RNN/Coffee Machine Consumption/'

# Load the dataset files using numpy's loadtxt function
# This converts the text files into numpy arrays
input_data = np.loadtxt(folder_path + 'Input_Data.txt', delimiter=',')
output_data = np.loadtxt(folder_path + 'Output_Data.txt', delimiter=',')

# Load the single values for maximum aggregated and appliance consumption
max_agg = np.loadtxt(folder_path + 'CoffeeMachinemaxAgg.txt')
max_app = np.loadtxt(folder_path + 'CoffeeMachinemaxApp.txt')

# Print the shapes and values to verify everything loaded correctly
print("Input Data Shape:", input_data.shape)
print("Output Data Shape:", output_data.shape)
print("Max Aggregated Consumption:", max_agg)
print("Max Appliance Consumption:", max_app)

"""* Plot drawing"""

import matplotlib.pyplot as plt
import random

# Total number of sequences (rows) in our data
total_sequences = input_data.shape[0]

# Rule: At least one plot must show the appliance turned on.
# We find all rows where the sum of the appliance consumption is greater than 0
active_appliance_indices = np.where(np.sum(output_data, axis=1) > 0)[0]

# 1. Pick one random index from the active ones
idx1 = random.choice(active_appliance_indices)
# 2. Pick two completely random indices for the other plots
idx2 = random.randint(0, total_sequences - 1)
idx3 = random.randint(0, total_sequences - 1)

# List of the 3 chosen sequences to plot
random_indices = [idx1, idx2, idx3]

# Loop to create 3 plots
for i, idx in enumerate(random_indices):
    # Create a figure and a primary axis
    fig, ax1 = plt.subplots(figsize=(10, 5))

    # --- Primary Y-Axis (Aggregated Consumption) ---
    color_agg = 'tab:blue'
    ax1.set_xlabel('Time (minutes)')
    ax1.set_ylabel('Aggregated Consumption (Watts)', color=color_agg)
    # Plot the input sequence on ax1
    line1 = ax1.plot(input_data[idx], color=color_agg, label='Aggregated (House)')
    ax1.tick_params(axis='y', labelcolor=color_agg)

    # --- Secondary Y-Axis (Appliance Consumption) ---
    # Create a twin axis sharing the same X-axis
    ax2 = ax1.twinx()
    color_app = 'tab:orange'
    ax2.set_ylabel('Appliance Consumption (Watts)', color=color_app)
    # Plot the output sequence on ax2
    line2 = ax2.plot(output_data[idx], color=color_app, label='Appliance (Coffee Machine)')
    ax2.tick_params(axis='y', labelcolor=color_app)

    # --- Title and Legend ---
    plt.title(f'Plot {i+1} - Sequence Row Index: {idx}')

    # Combine the legends from both axes into one
    lines = line1 + line2
    labels = [l.get_label() for l in lines]
    ax1.legend(lines, labels, loc='upper left')

    # Add a grid and display the plot
    ax1.grid(True, linestyle='--', alpha=0.6)
    plt.savefig(f'plot_{i+1}.png')
    plt.show()

"""* Normalization"""

# 1. Normalization
# Divide input and output data by their respective maximum values
# This scales all values to be between 0 and 1
X_normalized = input_data / max_agg
y_normalized = output_data / max_app

"""* Reshaping the data"""

# 2. Reshape the data for RNNs (Samples, Timesteps, Features)
# We add a 3rd dimension since we have 1 feature (Power) per timestep
X_normalized = np.expand_dims(X_normalized, axis=-1)
y_normalized = np.expand_dims(y_normalized, axis=-1)

"""* Creating the indices"""

# 3. Create indices and shuffle them randomly
total_samples = X_normalized.shape[0]
indices = np.arange(total_samples)

# Set a random seed so we get the exact same random split every time we run the code
np.random.seed(42)
np.random.shuffle(indices)

"""* Train, Validation and Test sets"""

# 4. Define split percentages: 70% Train, 15% Validation, 15% Test
train_split = int(0.7 * total_samples)
val_split = int(0.85 * total_samples) # 70% + 15% = 85%

# Generate the specific indices for each set
train_idx = indices[:train_split]
val_idx = indices[train_split:val_split]
test_idx = indices[val_split:]

"""* Printing the shape"""

# 5. Create the final datasets using the indices
X_train, y_train = X_normalized[train_idx], y_normalized[train_idx]
X_val, y_val = X_normalized[val_idx], y_normalized[val_idx]
X_test, y_test = X_normalized[test_idx], y_normalized[test_idx]

# Print shapes to verify
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}, y_val shape: {y_val.shape}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")

"""* Models Architecture"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, GRU, SimpleRNN
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import MeanSquaredError

# Get sequence length and input dimensions automatically from the shape of our training data
seq_length = X_train.shape[1]
input_dim = X_train.shape[2]
output_dim = 1 # We want to predict 1 value per timestep (Appliance consumption)

"""* RNN model"""

# ==========================================
# 1. Build Simple RNN Model
# ==========================================
model_rnn = Sequential(name="RNN_Model")
model_rnn.add(SimpleRNN(64, input_shape=(seq_length, input_dim), return_sequences=True))
# The Dense layer outputs the final prediction for each timestep
model_rnn.add(Dense(output_dim))
model_rnn.compile(optimizer=Adam(learning_rate=0.001), loss=MeanSquaredError())

"""* LSTM model"""

# ==========================================
# 2. Build LSTM Model
# ==========================================
model_lstm = Sequential(name="LSTM_Model")
model_lstm.add(LSTM(64, input_shape=(seq_length, input_dim), return_sequences=True))
model_lstm.add(Dense(output_dim))
model_lstm.compile(optimizer=Adam(learning_rate=0.001), loss=MeanSquaredError())

"""* GRU model"""

# ==========================================
# 3. Build GRU Model
# ==========================================
model_gru = Sequential(name="GRU_Model")
model_gru.add(GRU(64, input_shape=(seq_length, input_dim), return_sequences=True))
model_gru.add(Dense(output_dim))
model_gru.compile(optimizer=Adam(learning_rate=0.001), loss=MeanSquaredError())

"""* Summaries of the models"""

# Print summaries to see the architecture details
print("--- RNN Summary ---")
model_rnn.summary()
print("\n--- LSTM Summary ---")
model_lstm.summary()
print("\n--- GRU Summary ---")
model_gru.summary()

"""* Training"""

from tensorflow.keras.callbacks import EarlyStopping

# Define Early Stopping callback
# monitor='val_loss': We watch the validation error
# patience=5: Stop if it doesn't improve for 5 epochs
# start_from_epoch=30: Wait until epoch 30 before starting to monitor (Satisfies the >= 30 epochs rule)
# restore_best_weights=True: When it stops, keep the weights of the best epoch, not the last one
early_stop = EarlyStopping(monitor='val_loss', patience=5, start_from_epoch=30, restore_best_weights=True)

# Set the maximum number of epochs and the batch size
max_epochs = 100
batch_size = 64

"""* RNN Training"""

# ==========================================
# 1. Train Simple RNN
# ==========================================
print("Training Simple RNN Model...")
history_rnn = model_rnn.fit(
    X_train, y_train,
    epochs=max_epochs,
    batch_size=batch_size,
    validation_data=(X_val, y_val),
    callbacks=[early_stop],
    verbose=1
)

"""* LSTM Training"""

# ==========================================
# 2. Train LSTM
# ==========================================
print("\nTraining LSTM Model...")
history_lstm = model_lstm.fit(
    X_train, y_train,
    epochs=max_epochs,
    batch_size=batch_size,
    validation_data=(X_val, y_val),
    callbacks=[early_stop],
    verbose=1
)

"""* GRU Training"""

# ==========================================
# 3. Train GRU
# ==========================================
print("\nTraining GRU Model...")
history_gru = model_gru.fit(
    X_train, y_train,
    epochs=max_epochs,
    batch_size=batch_size,
    validation_data=(X_val, y_val),
    callbacks=[early_stop],
    verbose=1
)

"""* Plot drawing"""

# ==========================================
# Print and Plot the Losses (Requirement 6d)
# ==========================================
def plot_history(history, model_name):
    train_loss = history.history['loss']
    val_loss = history.history['val_loss']

    # Print final losses
    print(f"\n--- {model_name} Final Losses ---")
    print(f"Training Loss: {train_loss[-1]:.6f}")
    print(f"Validation Loss: {val_loss[-1]:.6f}")

    # Plot losses
    plt.figure(figsize=(8, 4))
    plt.plot(train_loss, label='Train Loss (MSE)')
    plt.plot(val_loss, label='Validation Loss (MSE)')
    plt.title(f'{model_name} Training History')
    plt.xlabel('Epoch')
    plt.ylabel('Loss (MSE)')
    plt.legend(loc='upper right')
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.savefig(f'{model_name}_training_history.png')
    plt.show()

# Call the plot function for each model
plot_history(history_rnn, "Simple RNN")
plot_history(history_lstm, "LSTM")
plot_history(history_gru, "GRU")

"""* Predictions"""

from sklearn.metrics import mean_squared_error, mean_absolute_error, max_error

# ==========================================
# 1. Generate Predictions for Train and Test sets
# ==========================================
print("Making predictions...")
# We use one model for train predictions as per instructions (let's use LSTM as representative)
train_pred_lstm = model_lstm.predict(X_train)

# Predict on test set for all three models to compare them
test_pred_rnn = model_rnn.predict(X_test)
test_pred_lstm = model_lstm.predict(X_test)
test_pred_gru = model_gru.predict(X_test)

"""* Denormalization"""

# ==========================================
# 2. Denormalization (Multiply by max_app)
# ==========================================
# We remove the last dimension using np.squeeze so shape goes from (samples, seq_length, 1) to (samples, seq_length)
y_test_denorm = np.squeeze(y_test) * max_app
test_pred_rnn_denorm = np.squeeze(test_pred_rnn) * max_app
test_pred_lstm_denorm = np.squeeze(test_pred_lstm) * max_app
test_pred_gru_denorm = np.squeeze(test_pred_gru) * max_app

"""* Metrics function"""

# ==========================================
# 3. Calculate metrics per sequence (Row-wise)
# ==========================================
n_test_sequences = y_test_denorm.shape[0]

def calculate_sequence_metrics(y_true, y_pred):
    """Calculates RMSE, MAE, and Max Error for each sequence individually."""
    # Calculate errors per sequence (axis=1 means across the time steps of each sequence)
    # Mean Squared Error first, then square root for RMSE
    rmse = np.sqrt(np.mean((y_true - y_pred)**2, axis=1))
    mae = np.mean(np.abs(y_true - y_pred), axis=1)
    max_err = np.max(np.abs(y_true - y_pred), axis=1)
    return rmse, mae, max_err

"""* Metrics of all 3 models"""

# Get the 3 metrics (arrays of length n) for all 3 models
rmse_rnn, mae_rnn, max_rnn = calculate_sequence_metrics(y_test_denorm, test_pred_rnn_denorm)
rmse_lstm, mae_lstm, max_lstm = calculate_sequence_metrics(y_test_denorm, test_pred_lstm_denorm)
rmse_gru, mae_gru, max_gru = calculate_sequence_metrics(y_test_denorm, test_pred_gru_denorm)

"""* RMSE metric"""

# ==========================================
# 4. Plot the results (1 plot per error type)
# ==========================================
x_axis = np.arange(n_test_sequences) # From 0 to n-1

# Plot 1: RMSE
plt.figure(figsize=(12, 5))
plt.plot(x_axis, rmse_rnn, label='Simple RNN', alpha=0.7)
plt.plot(x_axis, rmse_lstm, label='LSTM', alpha=0.7)
plt.plot(x_axis, rmse_gru, label='GRU', alpha=0.7)
plt.title('RMSE per Test Sequence')
plt.xlabel('Test Sequence Index')
plt.ylabel('RMSE (Watts)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.savefig('rmse_per_sequence.png')
plt.show()

"""* MAE metric"""

# Plot 2: MAE
plt.figure(figsize=(12, 5))
plt.plot(x_axis, mae_rnn, label='Simple RNN', alpha=0.7)
plt.plot(x_axis, mae_lstm, label='LSTM', alpha=0.7)
plt.plot(x_axis, mae_gru, label='GRU', alpha=0.7)
plt.title('MAE per Test Sequence')
plt.xlabel('Test Sequence Index')
plt.ylabel('MAE (Watts)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.savefig('mae_per_sequence.png')
plt.show()

"""* Max Error"""

# Plot 3: Max Error
plt.figure(figsize=(12, 5))
plt.plot(x_axis, max_rnn, label='Simple RNN', alpha=0.7)
plt.plot(x_axis, max_lstm, label='LSTM', alpha=0.7)
plt.plot(x_axis, max_gru, label='GRU', alpha=0.7)
plt.title('Max Error per Test Sequence')
plt.xlabel('Test Sequence Index')
plt.ylabel('Max Error (Watts)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.savefig('max_error_per_sequence.png')
plt.show()

"""* ON & OFF sequences"""

# ==========================================
# 1. Identify ON and OFF sequences in the Test Set
# ==========================================
# Sum the actual consumption for each sequence
sequence_sums = np.sum(y_test_denorm, axis=1)

# Find the indices where the appliance was ON (sum > 0) and OFF (sum == 0)
# We use a very small threshold (e.g., 1e-5) for OFF just in case of floating point inaccuracies
on_indices = np.where(sequence_sums > 1e-5)[0]
off_indices = np.where(sequence_sums <= 1e-5)[0]

"""* Step 8"""

# ==========================================
# 2. Select 4 sequences (2 ON, 2 OFF)
# ==========================================
# Set random seed to get the same 4 plots every time you run this cell
random.seed(42)

# Select 2 random indices from the ON list and 2 from the OFF list
selected_on = random.sample(list(on_indices), 2)
selected_off = random.sample(list(off_indices), 2)

# Combine them into a single list
selected_indices = selected_on + selected_off
status_labels = ["Appliance ON", "Appliance ON", "Appliance OFF", "Appliance OFF"]

"""* 4 Separate plots"""

# ==========================================
# 3. Create 4 separate plots
# ==========================================
for i, idx in enumerate(selected_indices):
    plt.figure(figsize=(10, 5))

    # Plot Ground Truth (Actual Consumption) as a bold dashed line
    plt.plot(y_test_denorm[idx], label='Actual (Ground Truth)', color='black', linewidth=2.5, linestyle='--')

    # Plot Predictions from all 3 models
    plt.plot(test_pred_rnn_denorm[idx], label='Simple RNN', alpha=0.8, color='tab:red')
    plt.plot(test_pred_lstm_denorm[idx], label='LSTM', alpha=0.8, color='tab:green')
    plt.plot(test_pred_gru_denorm[idx], label='GRU', alpha=0.8, color='tab:blue')

    # Add title, labels, legend, and grid
    plt.title(f'Test Sequence Index: {idx} ({status_labels[i]})')
    plt.xlabel('Time (minutes)')
    plt.ylabel('Appliance Consumption (Watts)')
    plt.legend(loc='upper right')
    plt.grid(True, linestyle='--', alpha=0.6)

    # Show the plot
    plt.savefig(f'test_sequence_{idx}.png')
    plt.show()